/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// ── Imports racine ────────────────────────────────────────────────────────────
import { Route as rootRouteImport } from './routes/__root'

// ── Routes citoyens ───────────────────────────────────────────────────────────
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as FilRouteImport } from './routes/fil'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as MesSignalementsRouteImport } from './routes/mes-signalements'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as UrgencesRouteImport } from './routes/urgences'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as VoisinsRouteImport } from './routes/voisins'
import { Route as AccueilRouteImport } from './routes/accueil'

// ── Routes admin ──────────────────────────────────────────────────────────────
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAlertesRouteImport } from './routes/admin/alertes'
import { Route as AdminEpciRouteImport } from './routes/admin/epci'
import { Route as AdminMessagerieRouteImport } from './routes/admin/messagerie'
import { Route as AdminPublicationsRouteImport } from './routes/admin/publications'
import { Route as AdminSignalementsRouteImport } from './routes/admin/signalements'
import { Route as AdminEvenementsRouteImport } from './routes/admin/evenements'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminUrgencesRouteImport } from './routes/admin/urgences'
import { Route as AdminRadioRouteImport } from './routes/admin/radio'
import { Route as AdminConsultationsRouteImport } from './routes/admin/consultations'
import { Route as AdminVoisinsRouteImport } from './routes/admin/voisins'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTerrainIndexRouteImport } from './routes/admin/terrain/index'
import { Route as AdminTerrainTraitesRouteImport } from './routes/admin/terrain/traites'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminAcceptInviteRouteImport } from './routes/admin/accept-invite'

// ── Routes plateforme (backoffice opérateur) ──────────────────────────────────
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformCollectivitesRouteImport } from './routes/platform/collectivites'
import { Route as PlatformUsersRouteImport } from './routes/platform/users'
import { Route as PlatformRssRouteImport } from './routes/platform/rss'
import { Route as PlatformPublishersRouteImport } from './routes/platform/publishers'
import { Route as PlatformSettingsRouteImport } from './routes/platform/settings'
import { Route as PlatformKnowledgeRouteImport } from './routes/platform/knowledge'
import { Route as PlatformModulesRouteImport } from './routes/platform/modules'
import { Route as PlatformOnboardingRouteImport } from './routes/platform/onboarding'
import { Route as PlatformRetentionRouteImport } from './routes/platform/retention'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform/analytics'
import { Route as PlatformPlansRouteImport } from './routes/platform/plans'
import { Route as PlatformTarificationRouteImport } from './routes/platform/tarification'
import { Route as PlatformAbonnementsRouteImport } from './routes/platform/abonnements'
import { Route as AdminAbonnementRouteImport } from './routes/admin/abonnement'
import { Route as PlatformPublicitesRouteImport } from './routes/platform/publicites'
import { Route as PlatformMonetizationRouteImport } from './routes/platform/monetization'
import { Route as PlatformMobileRouteImport } from './routes/platform/mobile'
import { Route as PlatformModerationRouteImport } from './routes/platform/moderation'
import { Route as PlatformUtilisateursRouteImport } from './routes/platform/utilisateurs'

// ── Déclarations de routes ────────────────────────────────────────────────────
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const FilRoute = FilRouteImport.update({
  id: '/fil',
  path: '/fil',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const MesSignalementsRoute = MesSignalementsRouteImport.update({
  id: '/mes-signalements',
  path: '/mes-signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRoute,
} satisfies BaseRouteOptions)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgencesRoute = UrgencesRouteImport.update({
  id: '/urgences',
  path: '/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const VoisinsRoute = VoisinsRouteImport.update({
  id: '/voisins',
  path: '/voisins',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertesRoute = AdminAlertesRouteImport.update({
  id: '/admin/alertes',
  path: '/admin/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEpciRoute = AdminEpciRouteImport.update({
  id: '/admin/epci',
  path: '/admin/epci',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagerieRoute = AdminMessagerieRouteImport.update({
  id: '/admin/messagerie',
  path: '/admin/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPublicationsRoute = AdminPublicationsRouteImport.update({
  id: '/admin/publications',
  path: '/admin/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignalementsRoute = AdminSignalementsRouteImport.update({
  id: '/admin/signalements',
  path: '/admin/signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvenementsRoute = AdminEvenementsRouteImport.update({
  id: '/admin/evenements',
  path: '/admin/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUrgencesRoute = AdminUrgencesRouteImport.update({
  id: '/admin/urgences',
  path: '/admin/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRadioRoute = AdminRadioRouteImport.update({
  id: '/admin/radio',
  path: '/admin/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/admin/consultations',
  path: '/admin/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoisinsRoute = AdminVoisinsRouteImport.update({
  id: '/admin/voisins',
  path: '/admin/voisins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTerrainIndexRoute = AdminTerrainIndexRouteImport.update({
  id: '/admin/terrain/',
  path: '/admin/terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTerrainTraitesRoute = AdminTerrainTraitesRouteImport.update({
  id: '/admin/terrain/traites',
  path: '/admin/terrain/traites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcceptInviteRoute = AdminAcceptInviteRouteImport.update({
  id: '/admin/accept-invite',
  path: '/admin/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)

const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCollectivitesRoute = PlatformCollectivitesRouteImport.update({
  id: '/platform/collectivites',
  path: '/platform/collectivites',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/platform/users',
  path: '/platform/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRssRoute = PlatformRssRouteImport.update({
  id: '/platform/rss',
  path: '/platform/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPublishersRoute = PlatformPublishersRouteImport.update({
  id: '/platform/publishers',
  path: '/platform/publishers',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/platform/settings',
  path: '/platform/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformKnowledgeRoute = PlatformKnowledgeRouteImport.update({
  id: '/platform/knowledge',
  path: '/platform/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformModulesRoute = PlatformModulesRouteImport.update({
  id: '/platform/modules',
  path: '/platform/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformOnboardingRoute = PlatformOnboardingRouteImport.update({
  id: '/platform/onboarding',
  path: '/platform/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRetentionRoute = PlatformRetentionRouteImport.update({
  id: '/platform/retention',
  path: '/platform/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/platform/analytics',
  path: '/platform/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPlansRoute = PlatformPlansRouteImport.update({
  id: '/platform/plans',
  path: '/platform/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTarificationRoute = PlatformTarificationRouteImport.update({
  id: '/platform/tarification',
  path: '/platform/tarification',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAbonnementsRoute = PlatformAbonnementsRouteImport.update({
  id: '/platform/abonnements',
  path: '/platform/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMonetizationRoute = PlatformMonetizationRouteImport.update({
  id: '/platform/monetization',
  path: '/platform/monetization',
  getParentRoute: () => rootRouteImport,
} as any)

const PlatformPublicitesRoute = PlatformPublicitesRouteImport.update({
  id: '/platform/publicites',
  path: '/platform/publicites',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminAbonnementRoute = AdminAbonnementRouteImport.update({
  id: '/admin/abonnement',
  path: '/admin/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)

const PlatformMobileRoute = PlatformMobileRouteImport.update({
  id: '/platform/mobile',
  path: '/platform/mobile',
  getParentRoute: () => rootRouteImport,
} as any)

const PlatformModerationRoute = PlatformModerationRouteImport.update({
  id: '/platform/moderation',
  path: '/platform/moderation',
  getParentRoute: () => rootRouteImport,
} as any)

const PlatformUtilisateursRoute = PlatformUtilisateursRouteImport.update({
  id: '/platform/utilisateurs',
  path: '/platform/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)

// ── Interfaces de types ───────────────────────────────────────────────────────
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/consultations': typeof ConsultationsRoute
  '/voisins': typeof VoisinsRoute
  '/evenements': typeof EvenementsRoute
  '/fil': typeof FilRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/messagerie': typeof MessagerieRoute
  '/mes-signalements': typeof MesSignalementsRoute
  '/onboarding': typeof OnboardingRoute
  '/demo': typeof DemoRoute
  '/merci': typeof MerciRoute
  '/profil': typeof ProfilRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/voisins': typeof AdminVoisinsRoute
  '/admin/epci': typeof AdminEpciRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/radio': typeof AdminRadioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/urgences': typeof AdminUrgencesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/terrain/': typeof AdminTerrainIndexRoute
  '/admin/terrain/traites': typeof AdminTerrainTraitesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/collectivites': typeof PlatformCollectivitesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/platform/rss': typeof PlatformRssRoute
  '/platform/publishers': typeof PlatformPublishersRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/knowledge': typeof PlatformKnowledgeRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/onboarding': typeof PlatformOnboardingRoute
  '/platform/retention': typeof PlatformRetentionRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/tarification': typeof PlatformTarificationRoute
  '/platform/abonnements': typeof PlatformAbonnementsRoute
  '/admin/abonnement': typeof AdminAbonnementRoute
  '/platform/publicites': typeof PlatformPublicitesRoute
  '/platform/monetization': typeof PlatformMonetizationRoute
  '/platform/mobile': typeof PlatformMobileRoute
  '/platform/moderation': typeof PlatformModerationRoute
  '/platform/utilisateurs': typeof PlatformUtilisateursRoute
  '/accueil': typeof AccueilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/evenements': typeof EvenementsRoute
  '/fil': typeof FilRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/messagerie': typeof MessagerieRoute
  '/mes-signalements': typeof MesSignalementsRoute
  '/onboarding': typeof OnboardingRoute
  '/demo': typeof DemoRoute
  '/merci': typeof MerciRoute
  '/profil': typeof ProfilRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/voisins': typeof VoisinsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/voisins': typeof AdminVoisinsRoute
  '/admin/epci': typeof AdminEpciRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/radio': typeof AdminRadioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/urgences': typeof AdminUrgencesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/terrain': typeof AdminTerrainIndexRoute
  '/admin/terrain/traites': typeof AdminTerrainTraitesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/platform': typeof PlatformIndexRoute
  '/platform/collectivites': typeof PlatformCollectivitesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/platform/rss': typeof PlatformRssRoute
  '/platform/publishers': typeof PlatformPublishersRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/knowledge': typeof PlatformKnowledgeRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/onboarding': typeof PlatformOnboardingRoute
  '/platform/retention': typeof PlatformRetentionRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/tarification': typeof PlatformTarificationRoute
  '/platform/abonnements': typeof PlatformAbonnementsRoute
  '/admin/abonnement': typeof AdminAbonnementRoute
  '/platform/publicites': typeof PlatformPublicitesRoute
  '/platform/monetization': typeof PlatformMonetizationRoute
  '/platform/mobile': typeof PlatformMobileRoute
  '/platform/moderation': typeof PlatformModerationRoute
  '/platform/utilisateurs': typeof PlatformUtilisateursRoute
  '/accueil': typeof AccueilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/evenements': typeof EvenementsRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/messagerie': typeof MessagerieRoute
  '/mes-signalements': typeof MesSignalementsRoute
  '/onboarding': typeof OnboardingRoute
  '/demo': typeof DemoRoute
  '/merci': typeof MerciRoute
  '/profil': typeof ProfilRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/voisins': typeof VoisinsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/voisins': typeof AdminVoisinsRoute
  '/admin/epci': typeof AdminEpciRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/radio': typeof AdminRadioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/urgences': typeof AdminUrgencesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/terrain/': typeof AdminTerrainIndexRoute
  '/admin/terrain/traites': typeof AdminTerrainTraitesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/collectivites': typeof PlatformCollectivitesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/platform/rss': typeof PlatformRssRoute
  '/platform/publishers': typeof PlatformPublishersRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/knowledge': typeof PlatformKnowledgeRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/onboarding': typeof PlatformOnboardingRoute
  '/platform/retention': typeof PlatformRetentionRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/tarification': typeof PlatformTarificationRoute
  '/platform/abonnements': typeof PlatformAbonnementsRoute
  '/admin/abonnement': typeof AdminAbonnementRoute
  '/platform/publicites': typeof PlatformPublicitesRoute
  '/platform/monetization': typeof PlatformMonetizationRoute
  '/platform/mobile': typeof PlatformMobileRoute
  '/platform/moderation': typeof PlatformModerationRoute
  '/platform/utilisateurs': typeof PlatformUtilisateursRoute
  '/accueil': typeof AccueilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/auth'
    | '/carte'
    | '/consultations'
    | '/voisins'
    | '/evenements'
    | '/fil'
    | '/forgot-password'
    | '/landing'
    | '/messagerie'
    | '/mes-signalements'
    | '/onboarding'
    | '/demo'
    | '/merci'
    | '/profil'
    | '/radio'
    | '/reset-password'
    | '/services'
    | '/signaler'
    | '/urgences'
    | '/admin/login'
    | '/admin/'
    | '/admin/alertes'
    | '/admin/consultations'
    | '/admin/voisins'
    | '/admin/epci'
    | '/admin/evenements'
    | '/admin/messagerie'
    | '/admin/publications'
    | '/admin/radio'
    | '/admin/services'
    | '/admin/signalements'
    | '/admin/urgences'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/terrain/'
    | '/admin/terrain/traites'
    | '/admin/reset-password'
    | '/admin/accept-invite'
    | '/platform/'
    | '/platform/collectivites'
    | '/platform/users'
    | '/platform/rss'
    | '/platform/publishers'
    | '/platform/settings'
    | '/platform/knowledge'
    | '/platform/modules'
    | '/platform/onboarding'
    | '/platform/retention'
    | '/platform/analytics'
    | '/platform/plans'
    | '/platform/tarification'
    | '/platform/abonnements'
    | '/admin/abonnement'
    | '/platform/publicites'
    | '/platform/monetization'
    | '/platform/mobile'
    | '/platform/moderation'
    | '/platform/utilisateurs'
    | '/accueil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/auth'
    | '/carte'
    | '/consultations'
    | '/voisins'
    | '/evenements'
    | '/fil'
    | '/forgot-password'
    | '/landing'
    | '/messagerie'
    | '/mes-signalements'
    | '/onboarding'
    | '/demo'
    | '/merci'
    | '/profil'
    | '/radio'
    | '/reset-password'
    | '/services'
    | '/signaler'
    | '/urgences'
    | '/admin/login'
    | '/admin'
    | '/admin/alertes'
    | '/admin/consultations'
    | '/admin/voisins'
    | '/admin/epci'
    | '/admin/evenements'
    | '/admin/messagerie'
    | '/admin/publications'
    | '/admin/radio'
    | '/admin/services'
    | '/admin/signalements'
    | '/admin/urgences'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/terrain'
    | '/admin/terrain/traites'
    | '/admin/reset-password'
    | '/admin/accept-invite'
    | '/platform'
    | '/platform/collectivites'
    | '/platform/users'
    | '/platform/rss'
    | '/platform/publishers'
    | '/platform/settings'
    | '/platform/knowledge'
    | '/platform/modules'
    | '/platform/onboarding'
    | '/platform/retention'
    | '/platform/analytics'
    | '/platform/plans'
    | '/platform/tarification'
    | '/platform/abonnements'
    | '/admin/abonnement'
    | '/platform/publicites'
    | '/platform/monetization'
    | '/platform/mobile'
    | '/platform/moderation'
    | '/platform/utilisateurs'
    | '/accueil'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/auth'
    | '/carte'
    | '/consultations'
    | '/voisins'
    | '/evenements'
    | '/fil'
    | '/forgot-password'
    | '/landing'
    | '/messagerie'
    | '/mes-signalements'
    | '/onboarding'
    | '/demo'
    | '/merci'
    | '/profil'
    | '/radio'
    | '/reset-password'
    | '/services'
    | '/signaler'
    | '/urgences'
    | '/admin/login'
    | '/admin/'
    | '/admin/alertes'
    | '/admin/consultations'
    | '/admin/voisins'
    | '/admin/epci'
    | '/admin/evenements'
    | '/admin/messagerie'
    | '/admin/publications'
    | '/admin/radio'
    | '/admin/services'
    | '/admin/signalements'
    | '/admin/urgences'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/terrain/'
    | '/admin/terrain/traites'
    | '/admin/reset-password'
    | '/admin/accept-invite'
    | '/platform/'
    | '/platform/collectivites'
    | '/platform/users'
    | '/platform/rss'
    | '/platform/publishers'
    | '/platform/settings'
    | '/platform/knowledge'
    | '/platform/modules'
    | '/platform/onboarding'
    | '/platform/retention'
    | '/platform/analytics'
    | '/platform/plans'
    | '/platform/tarification'
    | '/platform/abonnements'
    | '/admin/abonnement'
    | '/platform/publicites'
    | '/platform/monetization'
    | '/platform/mobile'
    | '/platform/moderation'
    | '/platform/utilisateurs'
    | '/accueil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AuthRoute: typeof AuthRoute
  CarteRoute: typeof CarteRoute
  ConsultationsRoute: typeof ConsultationsRoute
  VoisinsRoute: typeof VoisinsRoute
  EvenementsRoute: typeof EvenementsRoute
  FilRoute: typeof FilRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  MessagerieRoute: typeof MessagerieRoute
  MesSignalementsRoute: typeof MesSignalementsRoute
  OnboardingRoute: typeof OnboardingRoute
  DemoRoute: typeof DemoRoute
  MerciRoute: typeof MerciRoute
  ProfilRoute: typeof ProfilRoute
  RadioRoute: typeof RadioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SignalerRoute: typeof SignalerRoute
  UrgencesRoute: typeof UrgencesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlertesRoute: typeof AdminAlertesRoute
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminVoisinsRoute: typeof AdminVoisinsRoute
  AdminEpciRoute: typeof AdminEpciRoute
  AdminEvenementsRoute: typeof AdminEvenementsRoute
  AdminMessagerieRoute: typeof AdminMessagerieRoute
  AdminPublicationsRoute: typeof AdminPublicationsRoute
  AdminRadioRoute: typeof AdminRadioRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSignalementsRoute: typeof AdminSignalementsRoute
  AdminUrgencesRoute: typeof AdminUrgencesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTerrainIndexRoute: typeof AdminTerrainIndexRoute
  AdminTerrainTraitesRoute: typeof AdminTerrainTraitesRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminAcceptInviteRoute: typeof AdminAcceptInviteRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformCollectivitesRoute: typeof PlatformCollectivitesRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
  PlatformRssRoute: typeof PlatformRssRoute
  PlatformPublishersRoute: typeof PlatformPublishersRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformKnowledgeRoute: typeof PlatformKnowledgeRoute
  PlatformModulesRoute: typeof PlatformModulesRoute
  PlatformOnboardingRoute: typeof PlatformOnboardingRoute
  PlatformRetentionRoute: typeof PlatformRetentionRoute
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  PlatformPlansRoute: typeof PlatformPlansRoute
  PlatformTarificationRoute: typeof PlatformTarificationRoute
  PlatformAbonnementsRoute: typeof PlatformAbonnementsRoute
  AdminAbonnementRoute: typeof AdminAbonnementRoute
  PlatformPublicitesRoute: typeof PlatformPublicitesRoute
  PlatformMonetizationRoute: typeof PlatformMonetizationRoute
  PlatformMobileRoute: typeof PlatformMobileRoute
  PlatformModerationRoute: typeof PlatformModerationRoute
  PlatformUtilisateursRoute: typeof PlatformUtilisateursRoute
  AccueilRoute: typeof AccueilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voisins': {
      id: '/voisins'
      path: '/voisins'
      fullPath: '/voisins'
      preLoaderRoute: typeof VoisinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fil': {
      id: '/fil'
      path: '/fil'
      fullPath: '/fil'
      preLoaderRoute: typeof FilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-signalements': {
      id: '/mes-signalements'
      path: '/mes-signalements'
      fullPath: '/mes-signalements'
      preLoaderRoute: typeof MesSignalementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRoute
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRoute
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgences': {
      id: '/urgences'
      path: '/urgences'
      fullPath: '/urgences'
      preLoaderRoute: typeof UrgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alertes': {
      id: '/admin/alertes'
      path: '/admin/alertes'
      fullPath: '/admin/alertes'
      preLoaderRoute: typeof AdminAlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/admin/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voisins': {
      id: '/admin/voisins'
      path: '/admin/voisins'
      fullPath: '/admin/voisins'
      preLoaderRoute: typeof AdminVoisinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/epci': {
      id: '/admin/epci'
      path: '/admin/epci'
      fullPath: '/admin/epci'
      preLoaderRoute: typeof AdminEpciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evenements': {
      id: '/admin/evenements'
      path: '/admin/evenements'
      fullPath: '/admin/evenements'
      preLoaderRoute: typeof AdminEvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messagerie': {
      id: '/admin/messagerie'
      path: '/admin/messagerie'
      fullPath: '/admin/messagerie'
      preLoaderRoute: typeof AdminMessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/publications': {
      id: '/admin/publications'
      path: '/admin/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AdminPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signalements': {
      id: '/admin/signalements'
      path: '/admin/signalements'
      fullPath: '/admin/signalements'
      preLoaderRoute: typeof AdminSignalementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/urgences': {
      id: '/admin/urgences'
      path: '/admin/urgences'
      fullPath: '/admin/urgences'
      preLoaderRoute: typeof AdminUrgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/terrain/': {
      id: '/admin/terrain/'
      path: '/admin/terrain'
      fullPath: '/admin/terrain/'
      preLoaderRoute: typeof AdminTerrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/terrain/traites': {
      id: '/admin/terrain/traites'
      path: '/admin/terrain/traites'
      fullPath: '/admin/terrain/traites'
      preLoaderRoute: typeof AdminTerrainTraitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accept-invite': {
      id: '/admin/accept-invite'
      path: '/admin/accept-invite'
      fullPath: '/admin/accept-invite'
      preLoaderRoute: typeof AdminAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/collectivites': {
      id: '/platform/collectivites'
      path: '/platform/collectivites'
      fullPath: '/platform/collectivites'
      preLoaderRoute: typeof PlatformCollectivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/platform/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/rss': {
      id: '/platform/rss'
      path: '/platform/rss'
      fullPath: '/platform/rss'
      preLoaderRoute: typeof PlatformRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/publishers': {
      id: '/platform/publishers'
      path: '/platform/publishers'
      fullPath: '/platform/publishers'
      preLoaderRoute: typeof PlatformPublishersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/platform/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/knowledge': {
      id: '/platform/knowledge'
      path: '/platform/knowledge'
      fullPath: '/platform/knowledge'
      preLoaderRoute: typeof PlatformKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/modules': {
      id: '/platform/modules'
      path: '/platform/modules'
      fullPath: '/platform/modules'
      preLoaderRoute: typeof PlatformModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/onboarding': {
      id: '/platform/onboarding'
      path: '/platform/onboarding'
      fullPath: '/platform/onboarding'
      preLoaderRoute: typeof PlatformOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/retention': {
      id: '/platform/retention'
      path: '/platform/retention'
      fullPath: '/platform/retention'
      preLoaderRoute: typeof PlatformRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/analytics': {
      id: '/platform/analytics'
      path: '/platform/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/plans': {
      id: '/platform/plans'
      path: '/platform/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof PlatformPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/tarification': {
      id: '/platform/tarification'
      path: '/platform/tarification'
      fullPath: '/platform/tarification'
      preLoaderRoute: typeof PlatformTarificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/abonnements': {
      id: '/platform/abonnements'
      path: '/platform/abonnements'
      fullPath: '/platform/abonnements'
      preLoaderRoute: typeof PlatformAbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/publicites': {
      id: '/platform/publicites'
      path: '/platform/publicites'
      fullPath: '/platform/publicites'
      preLoaderRoute: typeof PlatformPublicitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/monetization': {
      id: '/platform/monetization'
      path: '/platform/monetization'
      fullPath: '/platform/monetization'
      preLoaderRoute: typeof PlatformMonetizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/mobile': {
      id: '/platform/mobile'
      path: '/platform/mobile'
      fullPath: '/platform/mobile'
      preLoaderRoute: typeof PlatformMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/moderation': {
      id: '/platform/moderation'
      path: '/platform/moderation'
      fullPath: '/platform/moderation'
      preLoaderRoute: typeof PlatformModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/utilisateurs': {
      id: '/platform/utilisateurs'
      path: '/platform/utilisateurs'
      fullPath: '/platform/utilisateurs'
      preLoaderRoute: typeof PlatformUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/abonnement': {
      id: '/admin/abonnement'
      path: '/admin/abonnement'
      fullPath: '/admin/abonnement'
      preLoaderRoute: typeof AdminAbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

// ── Arbre de routes ───────────────────────────────────────────────────────────
const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ActualitesRoute,
  AuthRoute,
  CarteRoute,
  ConsultationsRoute,
  VoisinsRoute,
  EvenementsRoute,
  FilRoute,
  ForgotPasswordRoute,
  LandingRoute,
  MessagerieRoute,
  MesSignalementsRoute,
  OnboardingRoute,
  DemoRoute,
  MerciRoute,
  ProfilRoute,
  RadioRoute,
  ResetPasswordRoute,
  ServicesRoute,
  SignalerRoute,
  UrgencesRoute,
  AdminLoginRoute,
  AdminIndexRoute,
  AdminAlertesRoute,
  AdminConsultationsRoute,
  AdminVoisinsRoute,
  AdminEpciRoute,
  AdminEvenementsRoute,
  AdminMessagerieRoute,
  AdminPublicationsRoute,
  AdminRadioRoute,
  AdminServicesRoute,
  AdminSignalementsRoute,
  AdminUrgencesRoute,
  AdminAnalyticsRoute,
  AdminSettingsRoute,
  AdminTerrainIndexRoute,
  AdminTerrainTraitesRoute,
  AdminResetPasswordRoute,
  AdminAcceptInviteRoute,
  PlatformIndexRoute,
  PlatformCollectivitesRoute,
  PlatformUsersRoute,
  PlatformRssRoute,
  PlatformPublishersRoute,
  PlatformSettingsRoute,
  PlatformKnowledgeRoute,
  PlatformModulesRoute,
  PlatformOnboardingRoute,
  PlatformRetentionRoute,
  PlatformAnalyticsRoute,
  PlatformPlansRoute,
  PlatformTarificationRoute,
  PlatformAbonnementsRoute,
  AdminAbonnementRoute,
  PlatformPublicitesRoute,
  PlatformMonetizationRoute,
  PlatformMobileRoute,
  PlatformModerationRoute,
  PlatformUtilisateursRoute,
  AccueilRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
