/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrgencesRouteImport } from './routes/urgences'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FilRouteImport } from './routes/fil'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSignalementsRouteImport } from './routes/admin/signalements'
import { Route as AdminAlertesRouteImport } from './routes/admin/alertes'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSignalementIdRouteImport } from './routes/services/signalement.$id'

const UrgencesRoute = UrgencesRouteImport.update({
  id: '/urgences',
  path: '/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FilRoute = FilRouteImport.update({
  id: '/fil',
  path: '/fil',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignalementsRoute = AdminSignalementsRouteImport.update({
  id: '/admin/signalements',
  path: '/admin/signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertesRoute = AdminAlertesRouteImport.update({
  id: '/admin/alertes',
  path: '/admin/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSignalementIdRoute = ServicesSignalementIdRouteImport.update({
  id: '/services/signalement/$id',
  path: '/services/signalement/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/actualites': typeof ActualitesRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/signalement/$id': typeof ServicesSignalementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/actualites': typeof ActualitesRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/signalement/$id': typeof ServicesSignalementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/actualites': typeof ActualitesRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/signalement/$id': typeof ServicesSignalementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carte'
    | '/fil'
    | '/onboarding'
    | '/profil'
    | '/signaler'
    | '/urgences'
    | '/actualites'
    | '/admin/alertes'
    | '/admin/signalements'
    | '/admin/'
    | '/services/'
    | '/services/signalement/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carte'
    | '/fil'
    | '/onboarding'
    | '/profil'
    | '/signaler'
    | '/urgences'
    | '/actualites'
    | '/admin/alertes'
    | '/admin/signalements'
    | '/admin'
    | '/services'
    | '/services/signalement/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/carte'
    | '/fil'
    | '/onboarding'
    | '/profil'
    | '/signaler'
    | '/urgences'
    | '/actualites'
    | '/admin/alertes'
    | '/admin/signalements'
    | '/admin/'
    | '/services/'
    | '/services/signalement/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CarteRoute: typeof CarteRoute
  FilRoute: typeof FilRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfilRoute: typeof ProfilRoute
  SignalerRoute: typeof SignalerRoute
  UrgencesRoute: typeof UrgencesRoute
  ActualitesRoute: typeof ActualitesRoute
  AdminAlertesRoute: typeof AdminAlertesRoute
  AdminSignalementsRoute: typeof AdminSignalementsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesSignalementIdRoute: typeof ServicesSignalementIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urgences': {
      id: '/urgences'
      path: '/urgences'
      fullPath: '/urgences'
      preLoaderRoute: typeof UrgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fil': {
      id: '/fil'
      path: '/fil'
      fullPath: '/fil'
      preLoaderRoute: typeof FilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPat