/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// ── Imports racine ────────────────────────────────────────────────────────────
import { Route as rootRouteImport } from './routes/__root'

// ── Routes citoyens ───────────────────────────────────────────────────────────
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as FilRouteImport } from './routes/fil'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as MesSignalementsRouteImport } from './routes/mes-signalements'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as UrgencesRouteImport } from './routes/urgences'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as LandingRouteImport } from './routes/landing'

// ── Routes admin ──────────────────────────────────────────────────────────────
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAlertesRouteImport } from './routes/admin/alertes'
import { Route as AdminEpciRouteImport } from './routes/admin/epci'
import { Route as AdminMessagerieRouteImport } from './routes/admin/messagerie'
import { Route as AdminPublicationsRouteImport } from './routes/admin/publications'
import { Route as AdminSignalementsRouteImport } from './routes/admin/signalements'
import { Route as AdminEvenementsRouteImport } from './routes/admin/evenements'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminUrgencesRouteImport } from './routes/admin/urgences'
import { Route as AdminRadioRouteImport } from './routes/admin/radio'

// ── Routes plateforme (backoffice opérateur) ──────────────────────────────────
import { Route as PlatformKnowledgeRouteImport } from './routes/platform/knowledge'
import { Route as PlatformModulesRouteImport } from './routes/platform/modules'
import { Route as PlatformOnboardingRouteImport } from './routes/platform/onboarding'
import { Route as PlatformRetentionRouteImport } from './routes/platform/retention'

// ── Déclarations de routes ────────────────────────────────────────────────────
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const FilRoute = FilRouteImport.update({
  id: '/fil',
  path: '/fil',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const MesSignalementsRoute = MesSignalementsRouteImport.update({
  id: '/mes-signalements',
  path: '/mes-signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgencesRoute = UrgencesRouteImport.update({
  id: '/urgences',
  path: '/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertesRoute = AdminAlertesRouteImport.update({
  id: '/admin/alertes',
  path: '/admin/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEpciRoute = AdminEpciRouteImport.update({
  id: '/admin/epci',
  path: '/admin/epci',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagerieRoute = AdminMessagerieRouteImport.update({
  id: '/admin/messagerie',
  path: '/admin/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPublicationsRoute = AdminPublicationsRouteImport.update({
  id: '/admin/publications',
  path: '/admin/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignalementsRoute = AdminSignalementsRouteImport.update({
  id: '/admin/signalements',
  path: '/admin/signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvenementsRoute = AdminEvenementsRouteImport.update({
  id: '/admin/evenements',
  path: '/admin/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUrgencesRoute = AdminUrgencesRouteImport.update({
  id: '/admin/urgences',
  path: '/admin/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRadioRoute = AdminRadioRouteImport.update({
  id: '/admin/radio',
  path: '/admin/radio',
  getParentRoute: () => rootRouteImport,
} as any)

const PlatformKnowledgeRoute = PlatformKnowledgeRouteImport.update({
  id: '/platform/knowledge',
  path: '/platform/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformModulesRoute = PlatformModulesRouteImport.update({
  id: '/platform/modules',
  path: '/platform/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformOnboardingRoute = PlatformOnboardingRouteImport.update({
  id: '/platform/onboarding',
  path: '/platform/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRetentionRoute = PlatformRetentionRouteImport.update({
  id: '/platform/retention',
  path: '/platform/retention',
  getParentRoute: () => rootRouteImport,
} as any)

// ── Interfaces de types ───────────────────────────────────────────────────────
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/messagerie': typeof MessagerieRoute
  '/mes-signalements': typeof MesSignalementsRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/epci': typeof AdminEpciRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/radio': typeof AdminRadioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/urgences': typeof AdminUrgencesRoute
  '/platform/knowledge': typeof PlatformKnowledgeRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/onboarding': typeof PlatformOnboardingRoute
  '/platform/retention': typeof PlatformRetentionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/messagerie': typeof MessagerieRoute
  '/mes-signalements': typeof MesSignalementsRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/epci': typeof AdminEpciRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/radio': typeof AdminRadioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/urgences': typeof AdminUrgencesRoute
  '/platform/knowledge': typeof PlatformKnowledgeRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/onboarding': typeof PlatformOnboardingRoute
  '/platform/retention': typeof PlatformRetentionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/messagerie': typeof MessagerieRoute
  '/mes-signalements': typeof MesSignalementsRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/epci': typeof AdminEpciRoute
  '/admin/evenements': typeof AdminEvenementsRoute
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/radio': typeof AdminRadioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/urgences': typeof AdminUrgencesRoute
  '/platform/knowledge': typeof PlatformKnowledgeRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/onboarding': typeof PlatformOnboardingRoute
  '/platform/retention': typeof PlatformRetentionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/auth'
    | '/carte'
    | '/fil'
    | '/forgot-password'
    | '/landing'
    | '/messagerie'
    | '/mes-signalements'
    | '/onboarding'
    | '/profil'
    | '/radio'
    | '/reset-password'
    | '/services'
    | '/signaler'
    | '/urgences'
    | '/admin/'
    | '/admin/alertes'
    | '/admin/epci'
    | '/admin/evenements'
    | '/admin/messagerie'
    | '/admin/publications'
    | '/admin/radio'
    | '/admin/services'
    | '/admin/signalements'
    | '/admin/urgences'
    | '/platform/knowledge'
    | '/platform/modules'
    | '/platform/onboarding'
    | '/platform/retention'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/auth'
    | '/carte'
    | '/fil'
    | '/forgot-password'
    | '/landing'
    | '/messagerie'
    | '/mes-signalements'
    | '/onboarding'
    | '/profil'
    | '/radio'
    | '/reset-password'
    | '/services'
    | '/signaler'
    | '/urgences'
    | '/admin'
    | '/admin/alertes'
    | '/admin/epci'
    | '/admin/evenements'
    | '/admin/messagerie'
    | '/admin/publications'
    | '/admin/radio'
    | '/admin/services'
    | '/admin/signalements'
    | '/admin/urgences'
    | '/platform/knowledge'
    | '/platform/modules'
    | '/platform/onboarding'
    | '/platform/retention'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/auth'
    | '/carte'
    | '/fil'
    | '/forgot-password'
    | '/landing'
    | '/messagerie'
    | '/mes-signalements'
    | '/onboarding'
    | '/profil'
    | '/radio'
    | '/reset-password'
    | '/services'
    | '/signaler'
    | '/urgences'
    | '/admin/'
    | '/admin/alertes'
    | '/admin/epci'
    | '/admin/evenements'
    | '/admin/messagerie'
    | '/admin/publications'
    | '/admin/radio'
    | '/admin/services'
    | '/admin/signalements'
    | '/admin/urgences'
    | '/platform/knowledge'
    | '/platform/modules'
    | '/platform/onboarding'
    | '/platform/retention'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AuthRoute: typeof AuthRoute
  CarteRoute: typeof CarteRoute
  FilRoute: typeof FilRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  MessagerieRoute: typeof MessagerieRoute
  MesSignalementsRoute: typeof MesSignalementsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfilRoute: typeof ProfilRoute
  RadioRoute: typeof RadioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SignalerRoute: typeof SignalerRoute
  UrgencesRoute: typeof UrgencesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlertesRoute: typeof AdminAlertesRoute
  AdminEpciRoute: typeof AdminEpciRoute
  AdminEvenementsRoute: typeof AdminEvenementsRoute
  AdminMessagerieRoute: typeof AdminMessagerieRoute
  AdminPublicationsRoute: typeof AdminPublicationsRoute
  AdminRadioRoute: typeof AdminRadioRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSignalementsRoute: typeof AdminSignalementsRoute
  AdminUrgencesRoute: typeof AdminUrgencesRoute
  PlatformKnowledgeRoute: typeof PlatformKnowledgeRoute
  PlatformModulesRoute: typeof PlatformModulesRoute
  PlatformOnboardingRoute: typeof PlatformOnboardingRoute
  PlatformRetentionRoute: typeof PlatformRetentionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fil': {
      id: '/fil'
      path: '/fil'
      fullPath: '/fil'
      preLoaderRoute: typeof FilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-signalements': {
      id: '/mes-signalements'
      path: '/mes-signalements'
      fullPath: '/mes-signalements'
      preLoaderRoute: typeof MesSignalementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgences': {
      id: '/urgences'
      path: '/urgences'
      fullPath: '/urgences'
      preLoaderRoute: typeof UrgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alertes': {
      id: '/admin/alertes'
      path: '/admin/alertes'
      fullPath: '/admin/alertes'
      preLoaderRoute: typeof AdminAlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/epci': {
      id: '/admin/epci'
      path: '/admin/epci'
      fullPath: '/admin/epci'
      preLoaderRoute: typeof AdminEpciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evenements': {
      id: '/admin/evenements'
      path: '/admin/evenements'
      fullPath: '/admin/evenements'
      preLoaderRoute: typeof AdminEvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messagerie': {
      id: '/admin/messagerie'
      path: '/admin/messagerie'
      fullPath: '/admin/messagerie'
      preLoaderRoute: typeof AdminMessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/publications': {
      id: '/admin/publications'
      path: '/admin/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AdminPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signalements': {
      id: '/admin/signalements'
      path: '/admin/signalements'
      fullPath: '/admin/signalements'
      preLoaderRoute: typeof AdminSignalementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/urgences': {
      id: '/admin/urgences'
      path: '/admin/urgences'
      fullPath: '/admin/urgences'
      preLoaderRoute: typeof AdminUrgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/radio': {
      id: '/admin/radio'
      path: '/admin/radio'
      fullPath: '/admin/radio'
      preLoaderRoute: typeof AdminRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/knowledge': {
      id: '/platform/knowledge'
      path: '/platform/knowledge'
      fullPath: '/platform/knowledge'
      preLoaderRoute: typeof PlatformKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/modules': {
      id: '/platform/modules'
      path: '/platform/modules'
      fullPath: '/platform/modules'
      preLoaderRoute: typeof PlatformModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/onboarding': {
      id: '/platform/onboarding'
      path: '/platform/onboarding'
      fullPath: '/platform/onboarding'
      preLoaderRoute: typeof PlatformOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/retention': {
      id: '/platform/retention'
      path: '/platform/retention'
      fullPath: '/platform/retention'
      preLoaderRoute: typeof PlatformRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

// ── Arbre de routes ───────────────────────────────────────────────────────────
const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ActualitesRoute,
  AuthRoute,
  CarteRoute,
  FilRoute,
  ForgotPasswordRoute,
  LandingRoute,
  MessagerieRoute,
  MesSignalementsRoute,
  OnboardingRoute,
  ProfilRoute,
  RadioRoute,
  ResetPasswordRoute,
  ServicesRoute,
  SignalerRoute,
  UrgencesRoute,
  AdminIndexRoute,
  AdminAlertesRoute,
  AdminEpciRoute,
  AdminEvenementsRoute,
  AdminMessagerieRoute,
  AdminPublicationsRoute,
  AdminRadioRoute,
  AdminServicesRoute,
  AdminSignalementsRoute,
  AdminUrgencesRoute,
  PlatformKnowledgeRoute,
  PlatformModulesRoute,
  PlatformOnboardingRoute,
  PlatformRetentionRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
