/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrgencesRouteImport } from './routes/urgences'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FilRouteImport } from './routes/fil'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSignalementsRouteImport } from './routes/admin/signalements'
import { Route as AdminAlertesRouteImport } from './routes/admin/alertes'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSignalementIdRouteImport } from './routes/services/signalement.$id'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformCommunesRouteImport } from './routes/platform/communes'
import { Route as PlatformUsersRouteImport } from './routes/platform/users'
import { Route as PlatformLicencesRouteImport } from './routes/platform/licences'
import { Route as PlatformStatsRouteImport } from './routes/platform/stats'
import { Route as PlatformSupportRouteImport } from './routes/platform/support'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'

const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)

const UrgencesRoute = UrgencesRouteImport.update({
  id: '/urgences',
  path: '/urgences',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FilRoute = FilRouteImport.update({
  id: '/fil',
  path: '/fil',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignalementsRoute = AdminSignalementsRouteImport.update({
  id: '/admin/signalements',
  path: '/admin/signalements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertesRoute = AdminAlertesRouteImport.update({
  id: '/admin/alertes',
  path: '/admin/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSignalementIdRoute = ServicesSignalementIdRouteImport.update({
  id: '/services/signalement/$id',
  path: '/services/signalement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCommunesRoute = PlatformCommunesRouteImport.update({
  id: '/platform/communes',
  path: '/platform/communes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/platform/users',
  path: '/platform/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLicencesRoute = PlatformLicencesRouteImport.update({
  id: '/platform/licences',
  path: '/platform/licences',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformStatsRoute = PlatformStatsRouteImport.update({
  id: '/platform/stats',
  path: '/platform/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSupportRoute = PlatformSupportRouteImport.update({
  id: '/platform/support',
  path: '/platform/support',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/actualites': typeof ActualitesRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/signalement/$id': typeof ServicesSignalementIdRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/communes': typeof PlatformCommunesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/platform/licences': typeof PlatformLicencesRoute
  '/platform/stats': typeof PlatformStatsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/confidentialite': typeof ConfidentialiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/actualites': typeof ActualitesRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/signalement/$id': typeof ServicesSignalementIdRoute
  '/platform': typeof PlatformIndexRoute
  '/platform/communes': typeof PlatformCommunesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/platform/licences': typeof PlatformLicencesRoute
  '/platform/stats': typeof PlatformStatsRoute
  '/platform/support': typeof PlatformSupportRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/confidentialite': typeof ConfidentialiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/fil': typeof FilRoute
  '/onboarding': typeof OnboardingRoute
  '/profil': typeof ProfilRoute
  '/signaler': typeof SignalerRoute
  '/urgences': typeof UrgencesRoute
  '/actualites': typeof ActualitesRoute
  '/admin/alertes': typeof AdminAlertesRoute
  '/admin/signalements': typeof AdminSignalementsRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/signalement/$id': typeof ServicesSignalementIdRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/communes': typeof PlatformCommunesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/platform/licences': typeof PlatformLicencesRoute
  '/platform/stats': typeof P